file: ../example/example.csv.gz
strata:
    - sex
    - age
seperator: ','
chunksize: 10000
codes:
    Primary_Diagnosis_Code: Primary_Diagnosis_Time
    Secondary_Diagnosis_Code_01: Secondary_Diagnosis_Time_01
    Secondary_Diagnosis_Code_02: Secondary_Diagnosis_Time_02
    Secondary_Diagnosis_Code_03: Secondary_Diagnosis_Time_03
    Secondary_Diagnosis_Code_04: Secondary_Diagnosis_Time_04
    Secondary_Diagnosis_Code_05: Secondary_Diagnosis_Time_05
    Secondary_Diagnosis_Code_06: Secondary_Diagnosis_Time_06
    Secondary_Diagnosis_Code_07: Secondary_Diagnosis_Time_07
    Secondary_Diagnosis_Code_08: Secondary_Diagnosis_Time_08
    Secondary_Diagnosis_Code_09: Secondary_Diagnosis_Time_09
    Secondary_Diagnosis_Code_10: Secondary_Diagnosis_Time_10
    Secondary_Diagnosis_Code_11: Secondary_Diagnosis_Time_11
    Secondary_Diagnosis_Code_12: Secondary_Diagnosis_Time_12
    Secondary_Diagnosis_Code_13: Secondary_Diagnosis_Time_13
    Secondary_Diagnosis_Code_14: Secondary_Diagnosis_Time_14
    Secondary_Diagnosis_Code_15: Secondary_Diagnosis_Time_15
    Secondary_Diagnosis_Code_16: Secondary_Diagnosis_Time_16
    Secondary_Diagnosis_Code_17: Secondary_Diagnosis_Time_17
    Secondary_Diagnosis_Code_18: Secondary_Diagnosis_Time_18
    Secondary_Diagnosis_Code_19: Secondary_Diagnosis_Time_19
    Secondary_Diagnosis_Code_20: Secondary_Diagnosis_Time_20
    Secondary_Diagnosis_Code_21: Secondary_Diagnosis_Time_21
    Secondary_Diagnosis_Code_22: Secondary_Diagnosis_Time_22
    Secondary_Diagnosis_Code_23: Secondary_Diagnosis_Time_23
    Secondary_Diagnosis_Code_24: Secondary_Diagnosis_Time_24
    Secondary_Diagnosis_Code_25: Secondary_Diagnosis_Time_25
